/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouSonGiaGoKimLoaiRouteImport } from './routes/thank-you-son-gia-go-kim-loai'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouSonGiaGoKimLoaiRoute = ThankYouSonGiaGoKimLoaiRouteImport.update({
  id: '/thank-you-son-gia-go-kim-loai',
  path: '/thank-you-son-gia-go-kim-loai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you-son-gia-go-kim-loai': typeof ThankYouSonGiaGoKimLoaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you-son-gia-go-kim-loai': typeof ThankYouSonGiaGoKimLoaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you-son-gia-go-kim-loai': typeof ThankYouSonGiaGoKimLoaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thank-you-son-gia-go-kim-loai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thank-you-son-gia-go-kim-loai'
  id: '__root__' | '/' | '/thank-you-son-gia-go-kim-loai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouSonGiaGoKimLoaiRoute: typeof ThankYouSonGiaGoKimLoaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you-son-gia-go-kim-loai': {
      id: '/thank-you-son-gia-go-kim-loai'
      path: '/thank-you-son-gia-go-kim-loai'
      fullPath: '/thank-you-son-gia-go-kim-loai'
      preLoaderRoute: typeof ThankYouSonGiaGoKimLoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouSonGiaGoKimLoaiRoute: ThankYouSonGiaGoKimLoaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
